{
 "title": "Modem Dashboard for Newtec",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SerialNumber",
    "label": "Modem Serial Number",
    "query": "66866, 2011, 5663, 4992, 20394, 2397, 5666, 23097, 20603, 71528, 70785, 66303, 66778, 71757, 71438, 69614"
   }
  ]
 },
 "panels": [
  {
   "title": "Current SNR",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'currentSNR' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'latency' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Downstream Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'dsAllocatedBw' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Upstream Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'usAllocatedBw' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hr." } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, round(cast(metric_value/3600 as numeric) ,2) FROM intel_metric\nWHERE metric_name = 'uptime' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Average Cn0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'usAvgCn0' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "Transmit Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'txPower' AND serial_no = '${SerialNumber}' "
    }
   ]
  },
  {
   "title": "CRC8 Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, metric_value FROM intel_metric\nWHERE metric_name = 'dvbS2Crc8Error' AND serial_no = '${SerialNumber}' "
    }
   ]
  }
 ]
}